### ISSUE TITLE
How to fix Dynamic Linking Error?

### ISSUE THREAD

**Issue by kim0z** [node-ffi/node-ffi#120]
Hi,
I read here about similar issues but it couldn't be helpful for my case.
my problem:

I wrote RunCmd.dll C++ on windows 7 which run synchronic command line(process), the dll was tested successfully using C#, but when using FFI module I got error:

```
C:\Program Files\nodejs\node_modules\ffi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: "RunCmd":
```

my code: (java script)

``` js
var nativeC = new ffi.Library("RunCmd", {
  "run_sync_process": ["void", ["LPTSTR"]]
});

console.log('running notepad');
var run = nativeC.run_sync_process;

run('notepad.exe');
```

I also try:

``` js
var libA = ffi.DynamicLibrary('RunCmd');
```

and got the same error
Any suggestion?

**Comment by PlasmaPower** [comment]
@TooTallNate We're having this problem over at cjlarose/argon2-ffi#20. We're trying to debug it there.

**Comment by TooTallNate** [comment]
@PlasmaPower Can you open a new issue with specifics please?

**Comment by tanzhi963** [comment]
This problem was solved today. The reason for the problem is that my x64 Node.js called the DLL file compiled by x86, which caused the problem. So, the solution is:
1. If you have the source code of the DLL, choose the same encoding method as your Node.js (for example, my Node.js is x64, and my DLL also chooses the x64 version to compile)
2. If you don't have the source code of the DLL, try reinstalling the Node.js installation package for x86 or x64.

![image](https://user-images.githubusercontent.com/15065391/170183087-45c9e8cf-eb1a-4a44-b9a4-f3f36f5c7de7.png)

![image](https://user-images.githubusercontent.com/15065391/170183215-25206d85-a331-49d1-979d-2684d26887d6.png)
