### ISSUE TITLE
GetLastError() always 0 when using Win32 API

### ISSUE THREAD

**Issue by isaacwaller** [node-ffi/node-ffi#261]
I'm using ffi to use Win32 APIs from node, however it is difficult to debug issues as GetLastError always returns 0. See comparison between C++ and ffi:

![c](https://github-cloud.s3.amazonaws.com/assets%2F107115%2F10956852%2Fda1f791e-8313-11e5-8c25-c99cd251598d.PNG)

![js](https://github-cloud.s3.amazonaws.com/assets%2F107115%2F10956855%2Fdbaa8af8-8313-11e5-8cce-e34dd77883db.PNG)

In the second screenshot it should print "Last error: 100". I think this might be an issue with ffi unless I am doing something wrong.

**Comment by unbornchikken** [comment]
Yup, that's behaves exactly in that way. FFI invokes SetLastError and GetLastError by using Win32 API calls those required to call them dynamically. So, GetLastError returns error code of that API that makes GetLastError ran. That will be always 0.

The only workaround is to implement your functionality to methods those gives back error code as a result.

**Comment by isaacwaller** [comment]
That makes sense, thank you.

**Comment by jptillman** [comment]
@unbornchikken That's not an acceptable workaround overall.  Win32 api functions are by nature NOT coded to return their error codes, and so your workaround is impossible for nearly all the windows api.  Since FFI is the one making the calls, it should capture the result of GetLastError() after making the user-designated calls and make it available to the user.  Since these error codes are the only way of identifying problems in Win32 api calls and GetLastError() is the only way of retrieving them, ffi's usability on win32 will be horrendous without this.
