### ISSUE TITLE
Calling a user given function from a callback

### ISSUE THREAD

**Issue by 0x1D0** [node-ffi/node-ffi#447]
'm linking with a C++ DLL, and the DLL function returns a struct. I don't want users using my library to deal with structs, and they have to add their own callback function to deal with the data too.

I made a ffi.Callback function, and the user's callback is one of the class' properties. However, I can't use the "this" keyword from inside the ffi.Callback function, so I can't call the user's callback.

Sample code:

```
function MyClass()
{
    this.eventHandler = null;


    this.listen = function() 
    {
        var callback = ffi.Callback('void', [infoStructure], 
            function(info)
            {
                // wrapping data in classes and sending to this.eventHandler
                this.eventHandler(someData);
            });

        process.on('exit', function() { callback });

        lib.someDllFunc(callback);
    };
}

var myClass = new MyClass();

myClass.eventHandler = function(someData) 
{
    // do something with data..
}

myClass.listen();
```

The callback can't access the class' members.

**Comment by addaleax** [comment]
You can always use [`.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to set the `this` context of a JS function if you want.

If you’re using Node >= 4.0.0 (which you should, because older versions are unsupported and have known security vunerabilities), you could also change `function(info) { … }` into `(info) => { … }` – using these “arrow functions” means that `this` inside the function is automatically the `this` from just outside the function.

**Comment by 0x1D0** [comment]
@addaleax Your solution works, thank you.
