### ISSUE TITLE
Library.js incorrectly assumes all Darwin binaries have .dylib extension

### ISSUE THREAD

**Issue by jarnoh** [node-ffi/node-ffi#47]
On OS X, many of the frameworks libraries have no special extension, still the library.js assumes it should append ".dylib" to every library path.  This makes it incompatible with many of the necessary built-in libraries, e.g.

```
var OSServices = new ffi.Library("/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices", { "UpdateSystemActivity": [ "int", [ "int" ] ] });
```

This code throws an error (OSX 10.7.3):

```
Error: Dynamic Linking Error: dlopen(/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.dylib, 2): image not found
    at new DynamicLibrary (/Users/jarnoh/node_modules/node-ffi/lib/dynamic_library.js:53:11)
    at new Library (/Users/jarnoh/node_modules/node-ffi/lib/library.js:15:12)
```

If I hack in to disable .dylib addition from library.js, the code works as expected.

**Comment by nathasion** [comment]
Hi

was this issue fixed in some way?
I still experience this, and I could not figure out how to call ffi.DynamicLibrary since this call does not allow me to specify which functions I need to get a pointer to...

Thanks for help
Nathaniel

**Comment by vgorloff** [comment]
> Hi
> 
> was this issue fixed in some way?
> I still experience this, and I could not figure out how to call ffi.DynamicLibrary since this call does not allow me to specify which functions I need to get a pointer to...
> 
> Thanks for help
> Nathaniel

This is what I did:

```
var dylib = ffi.DynamicLibrary('/Path/To/My/Framework.framework/Framework')
var func = ffi.ForeignFunction(dylib.get('my_symbol'), 'void', [ 'string', 'string' ])
func("hello", "hello")
```

**Comment by petertorelli** [comment]
I think the default behavior of adding an extension is odd to begin with. Why modify the user-specified path? If this is normal OS behavior, and since dlopen already has to do its own searching, it makes sense that the module make a small effort to do the same with the extension.

One solution, how about removing these [lines](https://github.com/node-ffi/node-ffi/blob/d9b843c03b35b99f205d001ebcbedd1b6c63b3d0/lib/library.js#L37-L40):

~~~
  if (libfile && libfile.indexOf(EXT) === -1) {
    debug('appending library extension to library name', EXT)
    libfile += EXT
  }
~~~

And let the user specify the extension if it fails ... or ... modify DynamicLibrary (dynamic_library.js) to -only- add the extension if the handle check is null, [here](https://github.com/node-ffi/node-ffi/blob/d9b843c03b35b99f205d001ebcbedd1b6c63b3d0/lib/dynamic_library.js#L44-L45):

```
  if (this._handle.isNull()) {
    var err = this.error()
```

Does this seem like a reasonable path to explore?
