### ISSUE TITLE
how to pass LPCWSTR to MessageBoxW?

### ISSUE THREAD

**Issue by maxzhou0** [node-ffi/node-ffi#496]
`'use strict';

var ffi = require('ffi');
const ref = require('ref');
var user32 = ffi.Library('user32', {
   'MessageBoxA': ['int32', [ 'int32', 'string', 'string', 'int32' ]]
   ,'MessageBoxW': ['int32', [ 'int32',ref.types.CString, ref.types.CString, 'int32' ]]
});

//user32.MessageBoxA(0,('aaaaa'),('aaaaaab'),1); 
user32.MessageBoxW(0,('なる'),('qqqqqqq'),1); 

`

this doesn't show proper words

**Comment by tinyAdapter** [comment]
"W version" of Win32 API uses UTF16 encoded CStrings, which is tagged as "ucs2" in Buffer module. So you must create a ucs2 buffer using ```Buffer.from("<SOME UNICODE>", "ucs2")``` and then pass it through MessageBoxW.

And, because this is a CString, you should also end the JS string with "\0" explicitly, otherwise it will not stop.

So, your code should now look like this:
```js
var ffi = require("ffi");
const ref = require("ref");
var user32 = ffi.Library("user32", {
  MessageBoxA: ["int32", ["int32", "string", "string", "int32"]],
  MessageBoxW: [
    "int32",
    ["int32", ref.types.CString, ref.types.CString, "int32"]
  ]
});

user32.MessageBoxW(
  0,
  Buffer.from("なる\0", "ucs2"),
  Buffer.from("qqqqqqq\0", "ucs2"),
  1
);
```

Tested on my Windows, works well.

By the way, if you're looking for more examples about calling Win32 API, check this library: https://github.com/waitingsong/node-win32-api/

**Comment by waitingsong** [comment]
@maxzhou0  `ucs2` is alias of `utf16le`, i prefer `ucs2` cause less char input~
