### ISSUE TITLE
crash in dll will cause node process/electron process crash

### ISSUE THREAD

**Issue by githoniel** [node-ffi/node-ffi#514]
if the function written in  C crash, like  out of range at memory location, cause the C code crash， and it will cause the `node process`/`electron renderer process` to crash

Can we catch these error in js and prevent the `node process`/`electron renderer process` from crash?

**Comment by repl-chris** [comment]
You generally can't even catch those errors in the C code, nevermind in javascript....and even when you can catch them usually it's no use anyways because memory corruption has already occurred, which is often what caused the crash in the first place.  These are much lower level problems - the C code is not executing in a sandbox that will protect you from non-recoverable errors like javascript does.  Your best bet is to fork the native calls into its own subprocess and communicate over ipc....if/when the subprocess crashes you just gracefully fork another one.

**Comment by githoniel** [comment]
thank you very much for your detailed explanation and sorry for my poor C knowledge.

I am now using the solution you suggest,  fork a child_process and use node-ffi in it。

It force every function to be async and make code a little complex.
