### ISSUE TITLE
Feature request: provide pre-compiled binaries (official builds) in npm packages

### ISSUE THREAD

**Issue by Mithgol** [node-ffi/node-ffi#53]
Currently `npm install ffi` requires building node-ffi from the source with node-gyp (on Windows the prerequisites are Python and MSVC, the latter is huge).

To get rid of this requirement (and thus to attract more end users and less building-related issues reported), please accomplish the following:
1. Require (and use) [node-bindings](https://github.com/TooTallNate/node-bindings/).
2. Compile binary part of node-ffi for the supported platforms (win32/ia32, darwin/x64, linux/ia32, linux/x64... sunos/ia32?), put the resulting binaries inside your npm package and let node-bindings pick one on user's side.
3. Put `binding.gyp` in `.npmignore`, otherwise npm will still attempt to build from the source. (Do not forget to add some contents of `.gitignore` to `.npmignore` when you create the latter, but only some: npm should not ignore the binaries.)
4. _(optional)_ Put binaries in `.gitignore` to prevent them from being hosted on GitHub. (This step is necessary only if you hate mixing sources with binaries. This step may also be completed already if you build in `build/`, which is currently in `.gitignore`.)

After that `npm install ffi` would involve only downloading and unpacking, and thus would _just work._

**Comment by kroggen** [comment]
Hi!

Is there any system to automatically make these builds now?

This would be very useful, mainly for Windows.

**Comment by kroggen** [comment]
Hi guys!

How can I contribute to this?

I am thinking about providing the binaries at least for Windows. It is really difficult to make this to work. I've got it in one machine and cannot compile on a second. So I guess that providing the pre-compiled would be better for all of us.

My doubt is: where to host the binary file to be downloaded?

I have one binary compiled for 32 bits and it is being used in a 64 bits machine too (with node and npm for 32 bits). Is it sufficient or we need one binary for x64?

**Comment by Mithgol** [comment]
It's been four years after the first thought of this issue. The Node.js ecosystem has grown a bit. There is [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp/) to help building addon binaries. It also might help with publishing binaries, but only on Amazon S3 hosting.

It's probably possible to alter `node-pre-gyp` in order to support an alternative, less centralized solution (for example, to run an [IPFS](https://ipfs.io/) daemon and to use [its JavaScript API](https://github.com/ipfs/js-ipfs-api/) to publish binaries on it). But I've never tried it.

**Comment by kroggen** [comment]
Hi Mithgol

My first thought was that I could generate a single or just 2 binary files for Windows manually, one for x86 and another for x64, and then publish then.

But now I noticed that we must have these for each node-abi.

So the automation would be welcome.

I am reading the node-pre-gyp docs to see how to implement this. Thank you for the link.

It supports publishing to Amazon S3 as well as to GitHub. And there is also the [node-pre-gyp-github](https://github.com/bchr02/node-pre-gyp-github).

For Windows we can use [appveyor](https://www.appveyor.com/) and for Linux and OSX there is [travis.ci](http://travis-ci.org/). I will focus on Windows because it is the hardest to compile.

They have all the required [build tools](https://www.appveyor.com/docs/installed-software/) for Windows as well as many node.js versions.

**Comment by kroggen** [comment]
Well, I will test with a forked project.

I just don't know if when accepting a pull request the Release will be migrated to the master branch.

**Comment by kroggen** [comment]
There is already an [appveyor.yml](https://github.com/node-ffi/node-ffi/blob/master/appveyor.yml) file in this repo. It is just not being used.

And there are recent binary files in this repo: https://github.com/Icenium/node-ffi

So it may not be that hard.
